Update

diff --git a/bin/set_wallpaper b/bin/set_wallpaper
--- a/bin/set_wallpaper
+++ b/bin/set_wallpaper
@@ -6,15 +6,17 @@ backend="$3"
 
 if [ -n "$wallpaper" -a -f "$wallpaper" ]; then
 
-    theme=$(basename $wallpaper) 
-    wpg ${backend:+"-b $backend"} -a $wallpaper && wpg -A $theme && wpg -s $theme
-
+    theme=$(basename $wallpaper)
     icons_path="/opt/oomox/plugins/icons_$icons"
+
+    wpg ${backend:+--backend "$backend"} -a $wallpaper && wpg -A $theme && wpg -s $theme
+
     if [ $? -eq 0 -a -n "$icons" -a -d "$icons_path" ]; then
         $icons_path/change_color.sh -o wal $HOME/.cache/wal/colors-oomox
         notify-send --icon=preferences-color "Icons colors changed!" "Colorized $icons using your wallpaper"
+    elif [ $? -ne 0 ]; then
+        notify-send --icon=error "Could not set theme" "Maybe try a different backend?"
     fi
-
 fi
 
 # vim:ft=sh
